In [1]:
1+1

2

In [3]:
import numpy as np

In [8]:
lst = [1,2,3,4,5]
np.array(lst)

array([1, 2, 3, 4, 5])

In [9]:
arr = np.array(lst)
type(arr)

numpy.ndarray

In [10]:
arr.shape

(5,)

In [11]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [12]:
##2 dimention
arr1.shape

(2, 3)

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [40]:
np.arange(50,1,-2).reshape(5,5)

array([[50, 48, 46, 44, 42],
       [40, 38, 36, 34, 32],
       [30, 28, 26, 24, 22],
       [20, 18, 16, 14, 12],
       [10,  8,  6,  4,  2]])

In [52]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [67]:
np.zeros(20).reshape((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [69]:
5 + np.ones((5,2,8))  ##brodcating

array([[[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]]])

In [70]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [71]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [74]:
print("random number generation (Uniform distridution)")
np.random.rand(2,3)

random number generation (Uniform distridution)


array([[0.30507882, 0.07608081, 0.69770263],
       [0.98817372, 0.19818921, 0.38532567]])

In [75]:
print("random number following a normal distribution with mean=0 and std =1")
print(np.random.randn(5,3))

random number following a normal distribution with mean=0 and std =1
[[ 0.5739632  -1.27172572  0.57044528]
 [-0.59056441  0.13895712  0.18744186]
 [ 1.37124678 -0.57675327  0.07441198]
 [-0.26660389  0.61700182 -1.55323192]
 [ 0.32693847  1.41839123  0.61269933]]


In [80]:
np.random.randint(1,100,50).reshape(10,5)


array([[98, 20, 29, 44, 56],
       [50, 94, 38, 99, 18],
       [84, 83, 16, 63, 79],
       [58, 43, 33, 15, 49],
       [70,  6, 76, 77, 99],
       [56,  8, 82, 24, 69],
       [95, 52, 93, 98, 65],
       [ 4, 38, 44, 82, 22],
       [61, 53,  6, 22, 15],
       [25, 55, 79, 99,  2]])

In [82]:
np.random.randint(1,100,(8,8))

array([[52,  5, 82, 34, 12, 37, 14,  7],
       [25, 34, 60, 64, 35, 72, 26, 52],
       [27, 67, 20,  5, 45, 85,  4, 22],
       [36, 78, 82, 83, 15, 94, 53, 28],
       [86,  2, 43, 87, 99, 68, 94, 75],
       [48, 72, 82, 20, 46, 32,  3, 87],
       [17,  7, 78, 75, 61, 75, 10, 86],
       [55, 73, 77, 33, 55, 69,  5, 47]])

In [86]:
##slicing
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr[-1:3:1]

array([], dtype=int32)

In [96]:
arr2 = np.random.randint(2,100,20).reshape(5,4)

In [97]:
arr2

array([[ 9, 80, 52, 43],
       [76, 10, 36, 74],
       [96, 38, 36, 96],
       [35, 67, 42, 35],
       [26, 94, 41, 79]])

In [98]:
arr2[0:3]

array([[ 9, 80, 52, 43],
       [76, 10, 36, 74],
       [96, 38, 36, 96]])

In [99]:
arr2[0:3,0:3]

array([[ 9, 80, 52],
       [76, 10, 36],
       [96, 38, 36]])

In [100]:
arr2[3:,1:]

array([[67, 42, 35],
       [94, 41, 79]])

In [108]:
arr2=np.random.randint(1,100,(3,3))
arr3=np.random.randint(20,100,(3,3))

In [113]:

arr2


array([[37, 32, 76],
       [69, 96, 87],
       [85, 68, 69]])

In [114]:
arr3

array([[45, 81, 30],
       [26, 28, 76],
       [58, 72, 61]])

In [115]:
arr2 +arr3

array([[ 82, 113, 106],
       [ 95, 124, 163],
       [143, 140, 130]])

In [116]:
arr2 / arr3

array([[0.82222222, 0.39506173, 2.53333333],
       [2.65384615, 3.42857143, 1.14473684],
       [1.46551724, 0.94444444, 1.13114754]])

In [117]:
np.sqrt(arr2)

array([[6.08276253, 5.65685425, 8.71779789],
       [8.30662386, 9.79795897, 9.32737905],
       [9.21954446, 8.24621125, 8.30662386]])

In [118]:
np.exp(arr3)

array([[3.49342711e+19, 1.50609731e+35, 1.06864746e+13],
       [1.95729609e+11, 1.44625706e+12, 1.01480039e+33],
       [1.54553894e+25, 1.85867175e+31, 3.10429794e+26]])

In [119]:
np.log10(arr3)

array([[1.65321251, 1.90848502, 1.47712125],
       [1.41497335, 1.44715803, 1.88081359],
       [1.76342799, 1.8573325 , 1.78532984]])

In [125]:
arr2[2:]=1000

In [126]:
arr2

array([[  37,   32,   76],
       [  69,   96,   87],
       [1000, 1000, 1000]])